# RandomForest Classificateur

In [4]:
#auteur I.CHELIKH 3704957

#import des librairies
import numpy as np
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import tree
from sklearn import metrics
from sklearn.decomposition import PCA
from scipy import optimize
from sklearn.model_selection import GridSearchCV 

from sklearn.ensemble import RandomForestClassifier

C:\Users\idris\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [5]:
# chargement des données

X_train, X_test, y_train, y_test = np.load('data.npy', allow_pickle = True)

In [6]:
# traitement et mise en forme

X_train=np.reshape(X_train,(X_train.shape[0],X_train.shape[1]*X_train.shape[2]))
print(np.shape(X_train))
X_test=np.reshape(X_test,(X_test.shape[0],X_test.shape[1]*X_test.shape[2]))
print(np.shape(X_test))

(1875, 144)
(625, 144)


In [32]:
# partie optimisation avec temps de calcul élevé ( plusieurs 10aines de minutes sur jupyter)
# méthode tirée de https://towardsdatascience.com/optimizing-hyperparameters-in-random-forest-classification-ec7741f9d3f6

"""
#déclaration est mise en forme des paramètres à faire varier sous forme de dictionnaire
n_estimators = [x for x in range(100,200,10)]
max_depth = [x for x in range(5,15,1)]

grid = {
    "n_estimators": n_estimators,
    "max_depth": max_depth
    }
    
RF = RandomForestClassifier(criterion='entropy', random_state=1)

#optimisiation des paramètres estimateurset profondeur
RF_Grid = GridSearchCV(estimator = RF, param_grid = grid, cv=5)

RF_Grid.fit(X_train, y_train)

print(RF_Grid.best_params_)

"""
print("vous pouvez décommenter le code dans cette cellule pour optimiser les paramètres du classificateur (temps de calcul très long)")

vous pouvez décommenter le code dans cette cellule pour optimiser les paramètres du classificateur (temps de calcul très long)


In [34]:
# partie avec les critères optimaux trouvés

RF = RandomForestClassifier(criterion='entropy', n_estimators=153,max_depth = 11, random_state=1)
RF.fit(X_train, y_train)

y_pred = RF.predict(X_test)

print("Taux de reconnaissance: ", metrics.accuracy_score(y_test, y_pred)*100, "%")

print("Matrice de Confusion associée : \n", metrics.confusion_matrix(y_test, y_pred))

Taux de reconnaissance:  92.16 %
Matrice de Confusion associée : 
 [[55  0  1  0  1  1  0  0  1  0]
 [ 0 67  0  3  0  1  0  0  0  0]
 [ 3  1 45  0  1  0  1  1  1  0]
 [ 0  1  0 53  0  1  0  2  0  0]
 [ 0  0  0  0 53  1  0  1  1  1]
 [ 0  1  2  1  3 62  0  0  1  0]
 [ 0  0  0  0  0  0 63  0  1  1]
 [ 0  0  0  0  1  0  0 67  6  0]
 [ 0  0  0  0  1  1  0  4 51  0]
 [ 1  0  0  0  0  0  1  0  0 60]]
